language: elixir
elixir:
  - 1.5.1
  - 1.6.1
otp_release:
  - 19.1
  - 19.3
  - 20.0

cache:
  directories:
    - _build
    - example/_build
    - deps

before_script:
  - mix deps.get
  - (cd example && mix deps.get)
  - MIX_ENV=test mix compile --warnings-as-errors
  - (cd example && MIX_ENV=test mix dialyzer --plt)
  - MIX_ENV=test mix dialyzer --plt

script:
  - MIX_ENV=test mix dialyzer --halt-exit-status
  - mix test
